#!/usr/bin/env python3
"""Bake the composer's sentence bank into src/gen/compose_data.c.

For every speaker/situation the game uses, the teacher's lines are split into an opening sentence and the rest,
and both parts are tokenized so NekoLM can score, on the device, how naturally a rest follows an opener. Only
splits whose tokens concatenate exactly into the whole line's tokens are kept. Run with the project venv:
  mkcompose.py [PER_POOL]   (default 40 openers and 40 rests per situation)

Approved pairs: where the ranking labellers (tools/rank_labels.py) have rated an opener's candidate continuations,
the pairs that all three rated fully sensible are baked in as the pool's approved list, and the game composes only
from those (NekoLM still picks among an opener's approved continuations). Every approved pair's text is checked
against the line the labellers saw, so a changed bank can never silently inherit another bank's approvals.
"""
import collections, glob, json, os, random, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from distill_spec import SITS  # noqa: E402
from nekolm import Tokenizer  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TAGS = json.load(open(os.path.join(ROOT, "content", "distill", "tags.json")))
PER = int(sys.argv[1]) if len(sys.argv) > 1 else 40
SPLIT = re.compile(r"(?<!Mr\.)(?<!Mrs\.)(?<!Ms\.)(?<=[.!?~])\s+(?=[A-Z\"'])")
SPLIT_LOWER = re.compile(r"(?<=[.!?~])\s+(?=[A-Za-z\"'])")
KEY_IDS = {"item": 1, "n": 2, "dir": 3}


def teacher_lines(spk, sit):
    out = []
    for d in ("raw", "raw2"):
        p = os.path.join(ROOT, "content", "distill", d, f"{spk}__{sit}.json")
        if os.path.exists(p):
            out += json.load(open(p))
    return out


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


LABELLERS = ["deepseek_deepseek-v4.1-flash", "minimax_minimax-m3", "xiaomi_mimo-v2.6-flash"]   # makes sense
VOICE = ["minimax_minimax-m3", "xiaomi_mimo-v2.6-flash"]     # in character (rank_labels.py --voice)


def label_records(kind, names):
    recs = {}
    for n in names:
        recs[n] = {}
        for path in (glob.glob(os.path.join(ROOT, "content", "rank", f"{kind}__{n}.jsonl")) +
                     glob.glob(os.path.join(ROOT, "build", "quality", "pool*", f"{kind}__{n}.jsonl"))):
            for line in open(path):
                r = json.loads(line)
                recs[n][r["id"]] = r
    return recs


def approvals():
    """(speaker, situation) -> {(opener, rest): the label record and position}: every pair all three labellers rated
    fully sensible and, where voice ratings exist, both voice labellers rated fully in character. A pair whose voice
    ratings are missing is not approved; with no voice ratings at all the rule is sense only (and says so)."""
    recs, voice = label_records("labels", LABELLERS), label_records("labels_v", VOICE)
    use_voice = all(voice[n] for n in VOICE) and os.environ.get("MKCOMPOSE_SENSE_ONLY") != "1"
    if not use_voice:
        print("mkcompose: approving on sense alone (no voice ratings, or MKCOMPOSE_SENSE_ONLY=1)")
    ok = collections.defaultdict(dict)
    first = recs[LABELLERS[0]]
    for gid, r in first.items():
        if not all(gid in recs[n] and recs[n][gid]["rests"] == r["rests"] for n in LABELLERS):
            continue
        if use_voice and not all(gid in voice[n] and voice[n][gid]["rests"] == r["rests"] for n in VOICE):
            continue
        for k, rest in enumerate(r["rests"]):
            if all(recs[n][gid]["sense"][k] == 2 for n in LABELLERS) and \
                    (not use_voice or all(voice[n][gid]["voice"][k] == 2 for n in VOICE)):
                ok[(r["spk"], r["sit"])][(r["op"], rest)] = (r, k)
    return ok


sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nlm_quality import c_fill  # noqa: E402
APPROVED = approvals()
tk = Tokenizer()
rng = random.Random(5)
out = ["/* Generated by tools/mkcompose.py - the composer's sentence bank (openers and rests, tokenized). */\n",
       '#include "../compose.h"\n\n']
pools, bank, kept, dropped, approved = [], [], 0, 0, 0
for spk, sit, desc in SITS:
    keys = re.findall(r"\{(\w+)\}", desc)
    key = KEY_IDS.get(keys[0], 0) if keys else 0
    split = SPLIT_LOWER if spk == "KITTEN" else SPLIT
    ops, rests = [], []
    for i, line in enumerate(teacher_lines(spk, sit)[:255]):
        parts = split.split(line)
        if len(parts) < 2:
            continue
        op, rest = parts[0], " ".join(parts[1:])
        t_op, t_rest = tk.encode(op.encode()), tk.encode((" " + rest).encode())
        if t_op + t_rest != tk.encode((op + " " + rest).encode()) or len(t_op) > 60 or len(t_rest) > 60:
            dropped += 1
            continue
        ops.append((i, op, t_op))
        rests.append((i, rest, t_rest))
    ops = rng.sample(ops, min(PER, len(ops)))
    rests = rng.sample(rests, min(PER, len(rests)))
    name = f"{spk}_{sit}".lower()
    for kind, units in (("op", ops), ("rest", rests)):
        for n, (i, text, toks) in enumerate(units):
            out.append(f"static const u16 {name}_{kind}{n}[] = {{{','.join(map(str, toks))}}};\n")
        out.append(f"static const CUnit {name}_{kind}[] = {{\n")
        out += [f"    {{ {cstr(text)}, {name}_{kind}{n}, {len(toks)}, {i}, {int('{' in text)}, {len(text)} }},\n"
                for n, (i, text, toks) in enumerate(units)]
        out.append("};\n")
        kept += len(units)
    pairs = sorted(APPROVED.get((spk, sit), {}))
    for (o, r) in pairs:                                 # the text must be exactly what the labellers rated
        rec, k = APPROVED[(spk, sit)][(o, r)]
        if c_fill(ops[o][1] + " " + rests[r][1], rec["value"], articles=False) != rec["lines"][k]:
            raise SystemExit(f"mkcompose: approved pair {spk}/{sit} {o}+{r} no longer matches its label; relabel")
    if pairs:
        out.append(f"static const u16 {name}_ok[] = {{{','.join(str(o << 8 | r) for o, r in pairs)}}};\n")
    approved += len(pairs)
    pools.append((TAGS["speakers"][spk], TAGS["situations"][sit], key, name, len(ops), len(rests), len(pairs)))
    bank.append({"spk": spk, "sit": sit, "key": key, "op": ops, "rest": rests, "ok": pairs})
json.dump(bank, open(os.path.join(ROOT, "build", "compose_bank.json"), "w"))   # the same bank, for the lab
out.append("\nconst CPool cpools[] = {\n")
out += [f"    {{ 0x{a:02X}, 0x{b:02X}, {k}, {n}_op, {n}_rest, {no}, {nr}, {n + '_ok' if na else '0'}, {na} }},\n"
        for a, b, k, n, no, nr, na in pools]
out.append(f"}};\nconst int cpool_count = {len(pools)};\n")
path = os.path.join(ROOT, "src", "gen", "compose_data.c")
open(path, "w").write("".join(out))
print(f"mkcompose: {len(pools)} situations, {kept} units ({dropped} splits dropped), {approved} approved pairs in "
      f"{sum(1 for p in pools if p[6])} situations -> src/gen/compose_data.c ({os.path.getsize(path) // 1024} KB)")
