#!/usr/bin/env python3
"""Bake a fallback bank of teacher lines into the game: src/gen/lines_data.c (up to K per situation).
They are shown when a situation cannot compose a line (src/live.c). Where the labellers rated a situation's whole
lines (tools/rank_labels.py whole ...), only lines all three found fully sensible and both voice labellers found
fully in character are kept (topped up to 4 with the best-rated if too few pass)."""
import collections, json, os, random, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAWS = [os.path.join(ROOT, "content", "distill", d) for d in ("raw", "raw2")]
TAGS = json.load(open(os.path.join(ROOT, "content", "distill", "tags.json")))
K = int(sys.argv[1]) if len(sys.argv) > 1 else 16
random.seed(3)


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


out = ["/* Generated by tools/mklines.py - teacher lines used as fallbacks. */\n", '#include "../lines.h"\n\n']
LABELLERS = ["deepseek_deepseek-v4.1-flash", "minimax_minimax-m3", "xiaomi_mimo-v2.6-flash"]
VOICE = ["minimax_minimax-m3", "xiaomi_mimo-v2.6-flash"]


def whole_ratings():
    """(speaker, situation) -> {line: (approved, score)} from the labellers' whole-line ratings."""
    recs = {}
    for n in LABELLERS:
        path = os.path.join(ROOT, "content", "rank", f"whole__{n}.jsonl")
        recs[n] = {r["id"]: r for r in map(json.loads, open(path))} if os.path.exists(path) else {}
    rated = collections.defaultdict(dict)
    for gid, r in recs[LABELLERS[0]].items():
        if not all(gid in recs[n] and recs[n][gid]["raw"] == r["raw"] for n in LABELLERS):
            continue
        for k, line in enumerate(r["raw"]):
            ok = all(recs[n][gid]["sense"][k] == 2 for n in LABELLERS) and all(recs[n][gid]["voice"][k] == 2 for n in VOICE)
            score = sum(recs[n][gid]["sense"][k] for n in LABELLERS) + sum(recs[n][gid]["voice"][k] for n in VOICE)
            rated[(r["spk"], r["sit"])][line] = (ok, score)
    return rated


RATED = whole_ratings()
index, approved = [], 0
for fn in sorted(os.listdir(RAWS[0])):
    spk, sit = fn[:-5].split("__")
    lines = [l for d in RAWS if os.path.exists(os.path.join(d, fn)) for l in json.load(open(os.path.join(d, fn)))]
    random.shuffle(lines)
    pick = lines[:K]
    rated = RATED.get((spk, sit))
    if rated:                                         # keep the random order, drop what the labellers rejected
        good = [l for l in lines if rated.get(l, (False, 0))[0]]
        if len(good) < 4:
            good += sorted((l for l in lines if l in rated and l not in good), key=lambda l: -rated[l][1])[:4 - len(good)]
        pick = good[:K]
        approved += 1
    name = f"pool_{spk}_{sit}".lower()
    out.append(f"static const char *const {name}[] = {{\n" + "".join(f"    {cstr(l)},\n" for l in pick) + "};\n")
    index.append((TAGS["speakers"][spk], TAGS["situations"][sit], name, len(pick)))
out.append("\nconst LinePool line_pools[] = {\n")
out += [f"    {{ 0x{a:02X}, 0x{b:02X}, {n}, {c} }},\n" for a, b, n, c in index]
out.append("};\nconst int line_pool_count = " + str(len(index)) + ";\n")
open(os.path.join(ROOT, "src", "gen", "lines_data.c"), "w").write("".join(out))
print(f"mklines: {len(index)} pools, up to {K} lines each ({approved} from labeller-approved lines)")
