#!/usr/bin/env python3
"""Procedural pixel painter for Neko Arcade dialogue busts (64x64, Prefect-Illustrious-style catgirls).

Writes art/bust.txt: a colour ramp shared by every character layer, then layers that the game stacks
in this order: outfit -> face -> eyes -> mouth -> hair -> ears -> accessory. Each layer is drawn with a
per-character ramp at run time, so one ear or face drawing serves every character.

Ramp slots (letters used in the sprites):
  k outline   s skin   d skin shadow   h/H/j hair or fur light/base/shadow   e eye dark   i iris
  w white (shine, ear fluff)   o/O/q outfit light/base/shadow   p pink (blush, inner ear)   m mouth   a accent
"""
import math, os

W = H = 64
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "art", "bust.txt")


class Canvas:
    def __init__(self, w=W, h=H):
        self.w, self.h = w, h
        self.g = [["."] * w for _ in range(h)]

    def get(self, x, y):
        return self.g[y][x] if 0 <= x < self.w and 0 <= y < self.h else "."

    def set(self, x, y, ch):
        if 0 <= x < self.w and 0 <= y < self.h:
            self.g[y][x] = ch

    def poly(self, pts, ch, only_over=None):
        """Scanline-fill a polygon (list of (x, y) floats)."""
        ys = [p[1] for p in pts]
        for y in range(max(0, int(min(ys))), min(self.h, int(math.ceil(max(ys))) + 1)):
            yc = y + 0.5
            xs = []
            for i in range(len(pts)):
                (x0, y0), (x1, y1) = pts[i], pts[(i + 1) % len(pts)]
                if (y0 <= yc < y1) or (y1 <= yc < y0):
                    xs.append(x0 + (yc - y0) * (x1 - x0) / (y1 - y0))
            xs.sort()
            for a, b in zip(xs[::2], xs[1::2]):
                for x in range(int(math.floor(a + 0.5)), int(math.floor(b + 0.5))):
                    if only_over is None or self.get(x, y) in only_over:
                        self.set(x, y, ch)

    def ellipse(self, cx, cy, rx, ry, ch, only_over=None, rows=None):
        for y in range(self.h):
            if rows and not (rows[0] <= y <= rows[1]):
                continue
            dy = (y + 0.5 - cy) / ry
            if abs(dy) > 1:
                continue
            hw = rx * math.sqrt(1 - dy * dy)
            for x in range(int(math.floor(cx - hw + 0.5)), int(math.floor(cx + hw + 0.5))):
                if only_over is None or self.get(x, y) in only_over:
                    self.set(x, y, ch)

    def outline(self, ch="k", inside=None, against=(".",)):
        """Turn every filled pixel that touches an 'against' pixel into the outline colour."""
        marks = []
        for y in range(self.h):
            for x in range(self.w):
                c = self.g[y][x]
                if c == "." or c == ch or (inside and c not in inside):
                    continue
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    if self.get(x + dx, y + dy) in against:
                        marks.append((x, y))
                        break
        for x, y in marks:
            self.set(x, y, ch)

    def mirror_from_left(self):
        for y in range(self.h):
            for x in range(self.w // 2):
                self.g[y][self.w - 1 - x] = self.g[y][x]

    def text(self):
        return "\n".join("".join(r) for r in self.g)


def sprite(name, c):
    return f"sprite {name} char\n{c.text()}\nend\n"


blocks = []
blocks.append("""# Generated by tools/paint_bust.py - edit the script, not this file.
ramp char
  k = 1 #2a1f33
  s = 2 #fff0e6
  d = 3 #f3c3b3
  h = 4 #6f86d6
  H = 5 #2e3152
  j = 6 #191a30
  e = 7 #34205e
  i = 8 #9a7ce0
  w = 9 #ffffff
  o = 10 #c9c5da
  O = 11 #8d88a6
  q = 12 #615c7c
  p = 13 #ff9ab4
  m = 14 #b8426e
  a = 15 #6aa8ff
end
""")

# ---------------------------------------------------------------- face (shared)
face = Canvas()
rows = {}
for y in range(18, 52):
    if y < 23:
        half = [9.5, 11.5, 12.5, 13.5, 14.5][y - 18]
    elif y <= 41:
        half = 16
    else:
        half = [15.5, 15.5, 14.5, 14.5, 13.5, 12.5, 11.5, 9.5, 7.5, 4.5][y - 42]
    rows[y] = half
    for x in range(int(32 - half), int(32 + half)):
        face.set(x, y, "s")
# neck
for y in range(49, 60):
    for x in range(27, 37):
        if face.get(x, y) == ".":
            face.set(x, y, "s")
face.outline("k")
# soft jaw shading and the shadow under the chin
for y in range(43, 51):
    half = rows[y]
    face.set(int(32 - half) + 1, y, "d")
    face.set(int(32 + half) - 2, y, "d")
for y in range(51, 55):
    for x in range(28, 36):
        if face.get(x, y) == "s":
            face.set(x, y, "d")
# tiny nose
face.set(32, 45, "d")
blocks.append(sprite("bust_face", face))

# ---------------------------------------------------------------- ears (shared, recoloured per character)


def ear_canvas(flat):
    c = Canvas()
    if not flat:
        outer = [(9, 3), (14, 24.5), (29, 16.5)]           # apex, outer base, inner base
        inner = [(12.5, 8.5), (16.5, 22), (25.5, 16.5)]
    else:
        outer = [(2, 13), (12, 27), (26, 17.5)]
        inner = [(6.5, 15.5), (13.5, 24.5), (22.5, 18)]
    c.poly(outer, "H")
    c.poly(inner, "p")
    # white fluff tufts growing out of the inner ear
    fx, fy = (inner[1][0] + inner[2][0]) / 2, (inner[1][1] + inner[2][1]) / 2
    for k, (dx, dy, n) in enumerate(((-3, -1, 4), (-1, -3, 5), (1, -2, 4), (-4, 1, 3))):
        for t in range(n):
            c.set(int(fx + dx - t * 0.6), int(fy + dy - t), "w")
            c.set(int(fx + dx - t * 0.6) + 1, int(fy + dy - t), "w")
    # light edge on the outer side, darker tip
    c.poly([outer[0], outer[1], (outer[1][0] + 1.5, outer[1][1] - 1.5), (outer[0][0] + 1.2, outer[0][1] + 2.5)], "h",
           only_over="H")
    ax, ay = outer[0]
    c.poly([(ax - 1, ay - 1), (ax + 4, ay + 5.5), (ax + 0.5, ay + 6.5)], "a", only_over="Hh")
    c.outline("k")
    c.mirror_from_left()
    return c


blocks.append(sprite("bust_ears_up", ear_canvas(False)))
blocks.append(sprite("bust_ears_flat", ear_canvas(True)))

# ---------------------------------------------------------------- eyes (patches 32x13 drawn at 16,32)
EYE_W, EYE_H = 32, 13


def eye_patch(kind):
    c = Canvas(EYE_W, EYE_H)

    def one(x0, mirror):
        def P(x, y, ch):
            c.set(x0 + (7 - x if mirror else x), y, ch)
        if kind in ("neutral", "wide", "sparkle"):
            top = 1 if kind != "wide" else 0
            # thick upper lash that flicks out and down at the outer corner (tareme), open sides
            for x in range(-1, 9):
                P(x, top, "k")
            for x in range(-2, 9):
                P(x, top + 1, "k")
            P(-2, top + 2, "k"); P(-3, top + 3, "k")
            # iris: rounded, dark at the top fading to the iris colour, darker rim at the sides
            shape = [(1, 7), (0, 8), (0, 8), (0, 8), (0, 8), (0, 8), (0, 8), (1, 7), (2, 6)]
            for k, (a, b) in enumerate(shape):
                y = top + 2 + k
                for x in range(a, b):
                    P(x, y, "e" if k < 3 or x in (a, b - 1) else "i")
            # short lower lash under the outer half
            for x in range(-1, 3):
                P(x, top + 11, "k")
            if kind == "wide":            # startled: shrink the iris, white shows around it
                for k, (a, b) in enumerate(shape):
                    y = top + 2 + k
                    P(a, y, "w"); P(b - 1, y, "w")
                    if k in (0, 8):
                        for x in range(a, b):
                            P(x, y, "w")
            # pupil and catchlights (big one upper left, small one lower right)
            for y in range(top + 5, top + 8):
                P(3, y, "e"); P(4, y, "e")
            P(1, top + 3, "w"); P(2, top + 3, "w"); P(1, top + 4, "w"); P(2, top + 4, "w"); P(3, top + 3, "w")
            P(5, top + 8, "w")
            if kind == "sparkle":         # star-shaped catchlight (Prefect "sparkling eyes")
                for (x, y) in ((5, top + 5), (4, top + 6), (5, top + 6), (6, top + 6), (5, top + 7)):
                    P(x, y, "w")
        elif kind == "happy":             # closed ^ ^
            for x, y in ((0, 7), (1, 6), (2, 5), (3, 4), (4, 4), (5, 5), (6, 6), (7, 7)):
                P(x, y, "k"); P(x, y + 1, "k")
            P(-1, 8, "k")
        elif kind == "half":              # half-lidded: lid down over the top of the iris
            for x in range(0, 9):
                P(x, 5, "k"); P(x, 6, "k")
            P(-1, 7, "k")
            for y in range(7, 12):
                P(0, y, "k"); P(8, y, "k")
            for x in range(1, 8):
                P(x, 12, "k")
            for y in range(7, 12):
                for x in range(1, 8):
                    P(x, y, "e" if y < 8 else "i")
            for y in range(8, 11):
                P(4, y, "e"); P(5, y, "e")
            P(2, 8, "w"); P(3, 8, "w"); P(5, 11, "w")
        elif kind == "closed":            # relaxed closed eyes, lashes down
            for x in range(0, 9):
                P(x, 8, "k")
            P(-1, 9, "k"); P(1, 9, "k"); P(3, 9, "k")
    one(4, False)     # viewer's left eye
    one(21, True)     # viewer's right eye (mirrored, outer corner on the right)
    return c


for kind in ("neutral", "happy", "half", "wide", "closed", "sparkle"):
    blocks.append(sprite(f"bust_eyes_{kind}", eye_patch(kind)))

# ---------------------------------------------------------------- mouths (patches 11x5 drawn at 27,46)


def mouth(kind):
    c = Canvas(11, 5)
    pat = {
        "cat":   ["..k.....k..", "...k.k.k...", "....k.k....", "...........", "..........."],
        "smile": ["..kkkkkkk..", "..kmmmmmk..", "...kmmmk...", "....kkk....", "..........."],
        "flat":  ["...........", "...kkkkk...", "...........", "...........", "..........."],
        "pout":  ["...........", "....kkk....", "...k...k...", "...........", "..........."],
        "open":  ["....kkk....", "...kmmmk...", "...kmmmk...", "....kkk....", "..........."],
        "smirk": ["...........", "...kk......", ".....kkkk..", "........k..", "..........."],
        "fang":  ["..kkkkkkk..", "..kwmmmmk..", "...kmmmk...", "....kkk....", "..........."],
    }[kind]
    for y, r in enumerate(pat):
        for x, ch in enumerate(r):
            if ch != ".":
                c.set(x, y, ch)
    return c


for kind in ("cat", "smile", "flat", "pout", "open", "smirk", "fang"):
    blocks.append(sprite(f"bust_mouth_{kind}", mouth(kind)))

# blush patch (drawn at 16,44 when a character is flustered or happy)
blush = Canvas(32, 3)
for x0 in (1, 23):
    for k in range(4):
        blush.set(x0 + 2 * k, 1, "p")
        blush.set(x0 + 2 * k + 1, 0, "p")
blocks.append(sprite("bust_blush", blush))

# ---------------------------------------------------------------- hair


def bangs(c, tips, top=26, x0=15, x1=49, strand="H"):
    """Pointed locks hanging from the hairline: tips = list of tip rows across the forehead.
    Each lock gets a darker seam on one edge and every other lock a thin highlight, so the fringe
    reads as separate strands instead of one mass."""
    n = len(tips)
    step = (x1 - x0) / n
    for k, tip in enumerate(tips):
        xa, xb = x0 + k * step - 1.2, x0 + (k + 1) * step + 1.2
        cx = (xa + xb) / 2 + (0.8 if k < n / 2 else -0.8)
        c.poly([(xa, top), (xb, top), (cx, tip)], strand)
    for k, tip in enumerate(tips):
        xa = x0 + k * step
        cx = xa + step / 2 + (0.8 if k < n / 2 else -0.8)
        # seam on every other lock: a short dark line toward the tip, so strands separate softly
        if k % 2 == 1:
            for t in range(0, max(0, tip - top - 8)):
                f = (t + 5) / max(1, tip - top)
                x = int(xa + (cx - xa) * f * 0.9)
                if c.get(x, top + 5 + t) == strand:
                    c.set(x, top + 5 + t, "j")
        if k % 2 == 0 and tip - top > 7:
            for t in range(2, (tip - top) // 2):
                x = int(cx - 1 + t * 0.1)
                if c.get(x, top + t) == strand:
                    c.set(x, top + t, "h")


def hair_nia():
    c = Canvas()
    # dome and the messy shoulder-length sides
    c.ellipse(32, 29, 19.5, 18.5, "H", rows=(9, 33))
    c.poly([(12.5, 26), (19.5, 26), (21, 44), (18, 55), (14, 57), (11.5, 44)], "H")
    c.poly([(51.5, 26), (44.5, 26), (43, 44), (46, 55), (50, 57), (52.5, 44)], "H")
    # messy flicks at the ends
    c.poly([(11.5, 50), (8.5, 57), (14, 56)], "H")
    c.poly([(52.5, 50), (55.5, 57), (50, 56)], "H")
    # overgrown fringe, one lock falling between the eyes
    bangs(c, [34, 37, 33, 36, 40, 35, 38, 34, 37, 33], top=24, x0=13.5, x1=50.5)
    # blue streaks through the fringe and a sheen band (her card: faint blue sheen)
    c.poly([(21, 18), (24, 18), (25, 36), (23, 36)], "a", only_over="H")
    c.poly([(40, 17), (42.5, 17), (41, 35), (39.5, 35)], "a", only_over="H")
    for x in range(20, 45):
        y = int(16 + ((x - 32) / 13) ** 2 * 3)
        if x % 5 != 0:
            c.set(x, y, "h")
            c.set(x, y + 1, "h")
    # shadow under the fringe and inside the side locks
    for x in range(14, 50):
        for y in range(26, 42):
            if c.get(x, y) == "H" and c.get(x, y + 1) == ".":
                c.set(x, y, "j")
    c.poly([(19, 30), (20.5, 30), (20, 47), (18.5, 47)], "j", only_over="H")
    c.poly([(45, 30), (43.5, 30), (44, 47), (45.5, 47)], "j", only_over="H")
    # ahoge: grows out of the crown and curls over
    for t in range(8):
        c.set(32 + t // 2, 11 - t, "H")
        c.set(33 + t // 2, 11 - t, "H")
    for (x, y) in ((37, 4), (38, 4), (38, 5), (39, 5), (39, 6)):
        c.set(x, y, "H")
    c.outline("k")
    return c


def hair_mako():
    c = Canvas()
    # short, sharp magenta bob with pointed tips
    c.ellipse(32, 29, 19, 18, "H", rows=(10, 33))
    c.poly([(13, 26), (20, 26), (20.5, 40), (16.5, 48), (12, 42)], "H")
    c.poly([(51, 26), (44, 26), (43.5, 40), (47.5, 48), (52, 42)], "H")
    bangs(c, [31, 35, 32, 36, 33, 37, 32, 35, 31], top=24, x0=14, x1=50)
    for x in range(19, 46):
        y = int(15 + ((x - 32) / 13) ** 2 * 3)
        if x % 6 != 0:
            c.set(x, y, "h"); c.set(x, y + 1, "h")
    for x in range(14, 50):
        for y in range(26, 40):
            if c.get(x, y) == "H" and c.get(x, y + 1) == ".":
                c.set(x, y, "j")
    c.outline("k")
    return c


def hair_shio():
    c = Canvas()
    # straight-cut, slightly overgrown mint bob; blunt fringe
    c.ellipse(32, 29, 19.5, 18.5, "H", rows=(10, 33))
    c.poly([(12.5, 26), (19.5, 26), (19.5, 52), (12.5, 52)], "H")
    c.poly([(51.5, 26), (44.5, 26), (44.5, 52), (51.5, 52)], "H")
    for x in range(13, 51):              # blunt fringe edge with a few uneven strands
        bottom = 33 + (1 if x % 7 == 3 else 0) + (-1 if x % 9 == 5 else 0)
        for y in range(24, bottom):
            c.set(x, y, "H")
    for x in range(12, 20):
        c.set(x, 52 + (x % 3 == 0), "H")
    for x in range(44, 52):
        c.set(x, 52 + (x % 3 == 1), "H")
    for x in range(19, 46):
        y = int(15 + ((x - 32) / 13) ** 2 * 3)
        if x % 7 != 0:
            c.set(x, y, "h"); c.set(x, y + 1, "h")
    for x in range(13, 51):
        for y in range(28, 36):
            if c.get(x, y) == "H" and c.get(x, y + 1) == ".":
                c.set(x, y, "j")
    c.poly([(18.5, 34), (19.5, 34), (19.5, 51), (18.5, 51)], "j", only_over="H")
    c.poly([(44.5, 34), (45.5, 34), (45.5, 51), (44.5, 51)], "j", only_over="H")
    c.outline("k")
    return c


def hair_mocha():
    c = Canvas()
    # cafe owner: long wavy hair tied in a low side ponytail, soft bangs swept aside
    c.ellipse(32, 29, 19.5, 18.5, "H", rows=(9, 33))
    c.poly([(12.5, 26), (19.5, 26), (21, 40), (17, 50), (12, 44)], "H")
    c.poly([(51.5, 26), (44.5, 26), (44, 36), (49, 46), (54, 58), (48, 62), (46, 50), (43, 40)], "H")
    bangs(c, [33, 35, 37, 36, 34, 32, 34, 31, 30], top=24, x0=13.5, x1=50.5)
    for x in range(19, 46):
        y = int(15 + ((x - 32) / 13) ** 2 * 3)
        if x % 5 != 2:
            c.set(x, y, "h"); c.set(x, y + 1, "h")
    for x in range(14, 50):
        for y in range(26, 40):
            if c.get(x, y) == "H" and c.get(x, y + 1) == ".":
                c.set(x, y, "j")
    c.poly([(47, 44), (49, 44), (51, 60), (49, 60)], "j", only_over="H")
    c.outline("k")
    return c


for name, fn in (("nia", hair_nia), ("mako", hair_mako), ("shio", hair_shio), ("mocha", hair_mocha)):
    blocks.append(sprite(f"bust_hair_{name}", fn()))

# ---------------------------------------------------------------- outfits


def outfit(kind):
    c = Canvas()
    # shoulders
    c.poly([(4, 64), (8, 57), (20, 53), (44, 53), (56, 57), (60, 64)], "O")
    if kind == "hoodie":                  # oversized hoodie, hood bunched behind the neck
        c.ellipse(32, 55, 17, 5, "o", rows=(50, 58))
        c.ellipse(32, 56, 9, 3.5, "q", rows=(53, 59))
        for y in range(58, 64):           # drawstrings
            c.set(27, y, "w"); c.set(37, y, "w")
        c.poly([(10, 64), (12, 59), (16, 64)], "q")
        c.poly([(54, 64), (52, 59), (48, 64)], "q")
    elif kind == "jacket":                # cropped jacket over a top, delicate chain necklace
        c.poly([(24, 53), (40, 53), (36, 64), (28, 64)], "o")
        c.poly([(24, 53), (29, 64), (22, 64), (19, 55)], "q")
        c.poly([(40, 53), (35, 64), (42, 64), (45, 55)], "q")
        for x in range(28, 37):
            c.set(x, 56 + (1 if 30 <= x <= 34 else 0), "a")
    elif kind == "cardigan":              # oversized oatmeal cardigan over a collared shirt
        c.poly([(25, 52), (39, 52), (35, 60), (29, 60)], "w")
        c.poly([(25, 52), (31, 58), (27, 60)], "o")
        c.poly([(39, 52), (33, 58), (37, 60)], "o")
        c.poly([(22, 53), (30, 64), (18, 64)], "q")
        c.poly([(42, 53), (34, 64), (46, 64)], "q")
        for y in (60, 63):
            c.set(32, y, "k")
    elif kind == "apron":                 # blouse and cafe apron with a bow
        c.poly([(25, 52), (39, 52), (37, 58), (27, 58)], "w")
        c.poly([(22, 57), (42, 57), (44, 64), (20, 64)], "o")
        for x in range(26, 39):
            c.set(x, 57, "a")
        c.poly([(29, 51), (32, 53.5), (29, 56)], "a")
        c.poly([(35, 51), (32, 53.5), (35, 56)], "a")
    c.outline("k")
    return c


for kind in ("hoodie", "jacket", "cardigan", "apron"):
    blocks.append(sprite(f"bust_outfit_{kind}", outfit(kind)))

# ---------------------------------------------------------------- accessories

glasses = Canvas()                          # Shio's round glasses, one lens smudged
for cx in (21.5, 42.5):
    for a in range(0, 360, 6):
        x = int(round(cx + 7.2 * math.cos(math.radians(a))))
        y = int(round(38.5 + 6.2 * math.sin(math.radians(a))))
        glasses.set(x, y, "k")
for x in range(29, 36):
    glasses.set(x, 37, "k")
for (x, y) in ((17, 35), (18, 34), (19, 34)):
    glasses.set(x, y, "w")
for (x, y) in ((45, 41), (46, 40), (44, 42), (46, 41)):
    glasses.set(x, y, "p")
blocks.append(sprite("bust_acc_glasses", glasses))

band = Canvas()                             # Mako's thin gem headband, slightly crooked
for x in range(15, 50):
    y = int(round(22 - (x - 15) * 0.09 + ((x - 32) / 17) ** 2 * -3))
    band.set(x, y, "a")
band.set(24, 20, "w"); band.set(25, 20, "a"); band.set(24, 21, "a"); band.set(25, 21, "w")
blocks.append(sprite("bust_acc_headband", band))

clip = Canvas()                             # Nia's hair clip
for (x, y) in ((44, 27), (45, 28), (46, 29), (46, 27), (44, 29)):
    clip.set(x, y, "a")
blocks.append(sprite("bust_acc_clip", clip))

bandana = Canvas()                          # Mocha's cafe kerchief
bandana.poly([(14, 21), (50, 21), (48, 24.5), (16, 24.5)], "a")
bandana.poly([(47, 21), (54, 17), (53, 23)], "a")
bandana.outline("k")
blocks.append(sprite("bust_acc_bandana", bandana))

open(OUT, "w", encoding="utf-8").write("\n".join(blocks))
print(f"paint_bust: {OUT}")
